webdriver.driver=provided
webdriver.provided.type=customdriver
webdriver.provided.customdriver=org.driver.wrappedDriver
webdriver.chrome.driver=libs/chromedriver.exe
serenity.outputDirectory=target/site/serenity1
serenity.requirement.types=theme,epic
show.pie.charts=false
serenity.project.name=SerenityIntegration
serenity.reports.show.step.details=true
serenity.logging=VERBOSE
serenity.verbose.steps=true
serenity.console.colors = true
serenity.threads=4
serenity.take.screenshots=DISABLED
# Base directory for the features
serenity.features.directory=src/test/resources/features

# Base directory for the requirements (if applicable)
serenity.requirements.dir=src/test/resources/features
